Repository NBCAMP-ToDwoong/todwoong, pull requests merged in 2024-03, with the labels that each got.

#23 [Feat] #22 - Tabbar 구현
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ToDwoong/ToDwoong/Global/App/SceneDelegate.swift
  ToDwoong/ToDwoong/Presentation/TabBar/TabBarController.swift
Labels: Feat

#28 [Chore]#27 - CoreData dueTime 속성 옵셔널 지정
  ToDwoong/ToDwoong/Global/CoreData/CoreDataManager.swift
Labels: Chore

#35 [Feat] #17 - 투두 추가화면 UI 구현
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/AddTodoMapPin.imageset/AddTodoMapPin 1.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/AddTodoMapPin.imageset/AddTodoMapPin 2.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/AddTodoMapPin.imageset/AddTodoMapPin.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/AddTodoMapPin.imageset/Contents.json
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DatePickerCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DateTimeOptionCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DateTimePickerContainerCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/InfoCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/TitleCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Protocols/AddTodoGroupSelectControllerDelegate.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Protocols/AddTodoLocationPickerDelegate.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Protocols/AddTodoLocationPickerViewDelegate.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Protocols/DateTimePickerDelegate.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Protocols/TitleCollectionViewCellDelegate.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/View/AddTodoLocationPickerView.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/View/AddTodoView.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoGroupSelectController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoLocationPickerViewController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoViewController.swift
Labels: Feat

#30 [Feat]#12 - 투두 리스트 UI 구현
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong/Presentation/TabBar/TabBarController.swift
  ToDwoong/ToDwoong/Presentation/TodoList/View/ContentSizeTableView.swift
  ToDwoong/ToDwoong/Presentation/TodoList/View/GroupCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/TodoList/View/TodoView.swift
  ToDwoong/ToDwoong/Presentation/TodoList/ViewController.swift
  ToDwoong/ToDwoong/Presentation/TodoList/ViewController/TodoViewController.swift
Labels: Feat

#36 [Feat] #24 - 투두추가 페이지 / 알림 선택 리스트 UI
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong/Global/Protocols/AddTodoGroupSelectControllerDelegate.swift
  ToDwoong/ToDwoong/Global/Protocols/AddTodoLocationPickerDelegate.swift
  ToDwoong/ToDwoong/Global/Protocols/AddTodoLocationPickerViewDelegate.swift
  ToDwoong/ToDwoong/Global/Protocols/DateTimePickerDelegate.swift
  ToDwoong/ToDwoong/Global/Protocols/TitleCollectionViewCellDelegate.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoAlarmViewController.swift
Labels: Feat

#40 [Feat]#11 - 카테고리 페이지 UI구현
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong/Global/Extensions/UIImage+Extension.swift
  ToDwoong/ToDwoong/Presentation/GroupList/View/ContentSizedTableView.swift
  ToDwoong/ToDwoong/Presentation/GroupList/View/ContentSizedViewCell.swift
  ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListTableViewCell.swift
  ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
  ToDwoong/ToDwoong/Presentation/GroupList/ViewController/GroupListViewController.swift
Labels: Feat

#42 [Feat]#41-코어데이터에 정렬을 위한 정수타입의 속성을 추가 및 readTodo와 sortTodo 메서드를 결합하여 호출시 정렬된 Todo배열 획득가능
  ToDwoong/ToDwoong/Global/CoreData/CoreDataManager.swift
  ToDwoong/ToDwoong/Global/CoreData/Model.xcdatamodeld/Model.xcdatamodel/contents
Labels: Feat

#44 [Feat] #33 - 디자인 시스템 업데이트
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ToDwoong/ToDwoong/Global/Extensions/UIColor+Extension.swift
  ToDwoong/ToDwoong/Presentation/TodoList/ViewController/TodoViewController.swift
Labels: Feat, Setting

#47 [Feat]#45-코어데이터 메서드 추가 및 변수 접근 등급 변경
  ToDwoong/ToDwoong/Global/CoreData/CoreDataManager.swift
Labels: Feat

#53 [Feat] #46 - 투두 추가 페이지 그룹 모달
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoGroupSelectController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoViewController.swift
Labels: Feat

#49 [Feat] #43 - 그룹 추가 페이지 UI 구현
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong/Presentation/AddGroup/View/AddGroupView.swift
  ToDwoong/ToDwoong/Presentation/AddGroup/ViewController/AddGroupViewController.swift
  ToDwoong/ToDwoong/Presentation/TodoList/View/ContentSizeTableView.swift
  ToDwoong/ToDwoong/Presentation/TodoList/View/TodoView.swift
  ToDwoong/ToDwoong/Presentation/TodoList/ViewController/TodoViewController.swift
Labels: Feat

#48 [Feat] #38 - 캘린더 UI 구현
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DatePickerCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DateTimeOptionCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DateTimePickerContainerCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/InfoCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/TitleCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Protocols/AddTodoGroupSelectControllerDelegate.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Protocols/AddTodoLocationPickerDelegate.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Protocols/AddTodoLocationPickerViewDelegate.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Protocols/DateTimePickerDelegate.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Protocols/TitleCollectionViewCellDelegate.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/View/AddTodoLocationPickerView.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoGroupSelectController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoGroupSelectController.swift~HEAD
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoGroupSelectController.swift~HEAD_0
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoGroupSelectController.swift~dev
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoGroupSelectController.swift~dev_0
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoLocationPickerViewController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoViewController.swift
  ToDwoong/ToDwoong/Presentation/Calander/ViewController/TodoCalandarController.swift
  ToDwoong/ToDwoong/Presentation/TabBar/TabBarController.swift
  ToDwoong/ToDwoong/Presentation/TodoList/ViewController/TodoViewController.swift
Labels: Chore, Feat

#58 Revert #57 "[Feat] #38 - 캘린더 UI 구현 (#48)"
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DatePickerCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DateTimeOptionCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DateTimePickerContainerCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/InfoCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/TitleCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Protocols/AddTodoGroupSelectControllerDelegate.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Protocols/AddTodoLocationPickerDelegate.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Protocols/AddTodoLocationPickerViewDelegate.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Protocols/DateTimePickerDelegate.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Protocols/TitleCollectionViewCellDelegate.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/View/AddTodoLocationPickerView.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoGroupSelectController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoGroupSelectController.swift~HEAD
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoGroupSelectController.swift~HEAD_0
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoGroupSelectController.swift~dev
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoGroupSelectController.swift~dev_0
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoLocationPickerViewController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoViewController.swift
  ToDwoong/ToDwoong/Presentation/Calander/ViewController/TodoCalandarController.swift
  ToDwoong/ToDwoong/Presentation/TabBar/TabBarController.swift
  ToDwoong/ToDwoong/Presentation/TodoList/ViewController/TodoViewController.swift
Labels: Bug, Fix

#50 [Feat]/#39-카테고리 코어데이터 세팅
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong/Global/CoreData/CoreDataManager.swift
  ToDwoong/ToDwoong/Global/Extensions/TDColor+Extension.swift
  ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListTableViewCell.swift
  ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
  ToDwoong/ToDwoong/Presentation/GroupList/ViewController/GroupListViewController.swift
Labels: Feat

#55 [Feat]#54-그룹 페이지 셀의 하단과 상단 크기값을 정적으로 지정
  ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
Labels: Fix

#60 [Feat]#38 - 캘린더 UI 구현
  ToDwoong/.swp
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/Dwong.imageset/Contents.json
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/Dwong.imageset/Dwong 1.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/Dwong.imageset/Dwong 2.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/Dwong.imageset/Dwong.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/Twong.imageset/Contents.json
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/Twong.imageset/Twong 1.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/Twong.imageset/Twong 2.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/Twong.imageset/Twong.png
  ToDwoong/ToDwoong/Presentation/Calander/ViewController/CalanderController.swift
  ToDwoong/ToDwoong/Presentation/TabBar/TabBarController.swift
Labels: Feat

#64 [Feat] #59 - 캘린더 기능구현
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong/Global/Protocols/AddTodoGroupSelectControllerDelegate.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/InfoCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/TitleCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoGroupSelectController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoViewController.swift
  ToDwoong/ToDwoong/Presentation/Calander/ViewController/CalanderController.swift
  ToDwoong/ToDwoong/Presentation/Calander/ViewController/CalanderViewController.swift
  ToDwoong/ToDwoong/Presentation/TabBar/TabBarController.swift
Labels: Feat

#62 [Feat] #56 - 그룹 추가 페이지 기능 구현
  ToDwoong/ToDwoong/Presentation/AddGroup/View/AddGroupView.swift
  ToDwoong/ToDwoong/Presentation/AddGroup/ViewController/AddGroupViewController.swift
Labels: Feat

#65 [Feat] #63 - 디자인 시스템 버전 업데이트
  ToDwoong/ToDwoong.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ToDwoong/ToDwoong/Presentation/TodoList/ViewController/TodoViewController.swift
Labels: Feat

#67 [Feat] #61 - 투두추가 기능 구현
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoViewController.swift
Labels: Feat

#68 [Feat] #31 - 투두리스트 기능(정렬, 분류, CRUD) 구현
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ToDwoong/ToDwoong/Global/Extensions/UIColor+Extension.swift
  ToDwoong/ToDwoong/Presentation/TabBar/TabBarController.swift
  ToDwoong/ToDwoong/Presentation/TodoList/View/ContentSizeTableView.swift
  ToDwoong/ToDwoong/Presentation/TodoList/View/GroupCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/TodoList/View/TodoListView.swift
  ToDwoong/ToDwoong/Presentation/TodoList/ViewController/TodoListViewController.swift
Labels: Feat

#75 [Feat] #70 - 커스텀 네비게이션바 구현 완료
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/ellipsis.imageset/Contents.json
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/ellipsis.imageset/ellipsis.png
  ToDwoong/ToDwoong/Presentation/TodoList/View/GroupCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/TodoList/View/TodoListView.swift
  ToDwoong/ToDwoong/Presentation/TodoList/ViewController/TodoListViewController.swift
Labels: Feat

#76 [Feat] #66 - 투두 수정 구현
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/TitleCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoViewController.swift
  ToDwoong/ToDwoong/Presentation/Calander/ViewController/CalanderViewController.swift
Labels: Feat

#77 [Feat] #37 - 온보딩, 런치스크린 페이지 UI 및 분기 구현
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong/Global/App/SceneDelegate.swift
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/appIcon.imageset/Contents.json
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/appIcon.imageset/appIcon@1x.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/appIcon.imageset/appIcon@2x.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/appIcon.imageset/appIcon@3x.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/dwoong.imageset/Contents.json
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/dwoong.imageset/dwoong@1x.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/dwoong.imageset/dwoong@2x.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/dwoong.imageset/dwoong@3x.png
  ToDwoong/ToDwoong/Presentation/LaunchScreen/View/LaunchScreenView.swift
  ToDwoong/ToDwoong/Presentation/LaunchScreen/View/OnboardingView.swift
  ToDwoong/ToDwoong/Presentation/LaunchScreen/ViewController/LaunchScreenViewController.swift
  ToDwoong/ToDwoong/Presentation/LaunchScreen/ViewController/OnboardingViewController.swift
Labels: Feat

#78 [Feat] #69 - 설정 모델 구현, 설정 페이지 구현
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong/Presentation/Preferences/Model/PreferencesModel.swift
  ToDwoong/ToDwoong/Presentation/Preferences/View/PreferencesTableViewCell.swift
  ToDwoong/ToDwoong/Presentation/Preferences/View/PreferencesView.swift
  ToDwoong/ToDwoong/Presentation/Preferences/ViewController/PreferencesViewController.swift
Labels: Feat

#79 Feat/#52-지도 페이지 기능 구현(UI일부)
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong/Global/Extensions/MapViewController+Extension.swift
  ToDwoong/ToDwoong/Presentation/Map/View/MapView.swift
  ToDwoong/ToDwoong/Presentation/Map/View/TodoAnnotation.swift
  ToDwoong/ToDwoong/Presentation/Map/View/TodoDetailView.swift
  ToDwoong/ToDwoong/Presentation/Map/ViewController/MapViewController.swift
  ToDwoong/ToDwoong/Presentation/Map/ViewController/TodoDetailViewController.swift
Labels: Feat

#81 [Chore] #74 코어데이터 설계 오류 수정
  ToDwoong/ToDwoong/Global/CoreData/CoreDataManager.swift
  ToDwoong/ToDwoong/Global/CoreData/Model.xcdatamodeld/Model.xcdatamodel/contents
  ToDwoong/ToDwoong/Presentation/AddGroup/ViewController/AddGroupViewController.swift
Labels: Chore

#88 [Chore]#80 - 투두리스트 세부사항 수정
  ToDwoong/ToDwoong/Global/App/SceneDelegate.swift
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/ellipsis.imageset/ellipsis.png
  ToDwoong/ToDwoong/Presentation/LaunchScreen/ViewController/OnboardingViewController.swift
  ToDwoong/ToDwoong/Presentation/TabBar/TabBarController.swift
  ToDwoong/ToDwoong/Presentation/TodoList/View/TodoListView.swift
  ToDwoong/ToDwoong/Presentation/TodoList/ViewController/TodoListViewController.swift
Labels: Chore

#92 [Feat] #89 - 그룹 추가 페이지 UI 및 기능 수정
  ToDwoong/ToDwoong/Presentation/AddGroup/View/AddGroupView.swift
  ToDwoong/ToDwoong/Presentation/AddGroup/ViewController/AddGroupViewController.swift
Labels: Feat

#90 [Chore]#83-캘린더 UI수정
  ToDwoong/ToDwoong.xcodeproj/xcshareddata/xcschemes/ToDwoong.xcscheme
  ToDwoong/ToDwoong/Presentation/Calander/ViewController/CalanderViewController.swift
Labels: Chore

#93 [Chore]#82-투두수정 위치 값 지도랜딩 및 검색기능 구현 및 수정
  ToDwoong/ToDwoong/Global/CoreData/CoreDataManager.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/View/AddTodoLocationPickerView.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoLocationPickerViewController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoViewController.swift
Labels: Chore

#95 [Feat]#94-투두추가 그룹 삭제기능
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/InfoCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoGroupSelectController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoViewController.swift
Labels: Feat

#97 [Chore]#96-투두 추가 UI 수정
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DatePickerCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DateTimeOptionCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DateTimePickerContainerCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/InfoCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/TitleCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/View/AddTodoView.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoViewController.swift
Labels: Chore

#98 [Feat]#51-지도 페이지 UI 및 기능 구현입니다.
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong/Global/Extensions/MapViewController+Extension.swift
  ToDwoong/ToDwoong/Global/Extensions/TodoAndCategory+Extension.swift
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/currentLocationIcon.imageset/Contents.json
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/currentLocationIcon.imageset/currentLocationIcon.png
  ToDwoong/ToDwoong/Presentation/Map/View/CustomCategoryChip.swift
  ToDwoong/ToDwoong/Presentation/Map/View/MapView.swift
  ToDwoong/ToDwoong/Presentation/Map/View/TodoAnnotation.swift
  ToDwoong/ToDwoong/Presentation/Map/ViewController/MapViewController.swift
  ToDwoong/ToDwoong/Presentation/Map/ViewController/TodoDetailViewController.swift
  ToDwoong/ToDwoong/Presentation/TabBar/TabBarController.swift
Labels: Feat

#100 [Feat] #99 - 프로젝트 설정 변경
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ToDwoong/ToDwoong.xcodeproj/xcshareddata/xcschemes/ToDwoong.xcscheme
  ToDwoong/ToDwoong/Global/App/AppDelegate.swift
  ToDwoong/ToDwoong/Global/App/SceneDelegate.swift
  ToDwoong/ToDwoong/Global/DesignSystem/ToDwoongDesign.framework/Headers/ToDwoongDesign-Swift.h
  ToDwoong/ToDwoong/Global/DesignSystem/ToDwoongDesign.framework/Headers/ToDwoongDesign.h
  ToDwoong/ToDwoong/Global/DesignSystem/ToDwoongDesign.framework/Info.plist
  ToDwoong/ToDwoong/Global/DesignSystem/ToDwoongDesign.framework/Modules/ToDwoongDesign.swiftmodule/Project/arm64-apple-ios-simulator.swiftsourceinfo
  ToDwoong/ToDwoong/Global/DesignSystem/ToDwoongDesign.framework/Modules/ToDwoongDesign.swiftmodule/arm64-apple-ios-simulator.abi.json
  ToDwoong/ToDwoong/Global/DesignSystem/ToDwoongDesign.framework/Modules/ToDwoongDesign.swiftmodule/arm64-apple-ios-simulator.swiftdoc
  ToDwoong/ToDwoong/Global/DesignSystem/ToDwoongDesign.framework/Modules/ToDwoongDesign.swiftmodule/arm64-apple-ios-simulator.swiftmodule
  ToDwoong/ToDwoong/Global/DesignSystem/ToDwoongDesign.framework/Modules/module.modulemap
  ToDwoong/ToDwoong/Global/DesignSystem/ToDwoongDesign.framework/ToDwoongDesign
  ToDwoong/ToDwoong/Global/DesignSystem/ToDwoongDesign.framework/_CodeSignature/CodeResources
  ToDwoong/ToDwoong/Global/Extensions/MapViewController+Extension.swift
  ToDwoong/ToDwoong/Global/Protocols/AddTodoGroupSelectControllerDelegate.swift
  ToDwoong/ToDwoong/Global/Protocols/AddTodoLocationPickerDelegate.swift
  ToDwoong/ToDwoong/Global/Protocols/AddTodoLocationPickerViewDelegate.swift
  ToDwoong/ToDwoong/Global/Protocols/AddTodoProtocols.swift
  ToDwoong/ToDwoong/Global/Protocols/DateTimePickerDelegate.swift
  ToDwoong/ToDwoong/Global/Protocols/TitleCollectionViewCellDelegate.swift
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/AppIcon.appiconset/Contents.json
  ToDwoong/ToDwoong/Presentation/AddGroup/View/AddGroupView.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DateTimePickerContainerCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/TitleCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/Calander/ViewController/CalanderViewController.swift
  ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
  ToDwoong/ToDwoong/Presentation/Map/View/CustomCategoryChip.swift
  ToDwoong/ToDwoong/Presentation/Map/View/MapView.swift
  ToDwoong/ToDwoong/Presentation/Map/ViewController/MapViewController.swift
  ToDwoong/ToDwoong/Presentation/Map/ViewController/TodoDetailViewController.swift
  ToDwoong/ToDwoong/Presentation/TabBar/TabBarController.swift
  ToDwoong/ToDwoong/Presentation/TodoList/View/GroupCollectionViewCell.swift
Labels: Feat

#101 [Feat] #91 - 플로팅 버튼
  ToDwoong/ToDwoong/Presentation/AddTodo/View/AddTodoView.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoViewController.swift
  ToDwoong/ToDwoong/Presentation/Map/ViewController/TodoDetailViewController.swift
  ToDwoong/ToDwoong/Presentation/TabBar/TabBarController.swift
Labels: Feat

#102 [Feat] #73 - 각 뷰컨트롤러 데이터 업데이트
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ToDwoong/ToDwoong/Global/Extensions/Notification+Extension.swift
  ToDwoong/ToDwoong/Presentation/AddGroup/View/AddGroupView.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoViewController.swift
  ToDwoong/ToDwoong/Presentation/Calander/ViewController/CalanderViewController.swift
  ToDwoong/ToDwoong/Presentation/GroupList/ViewController/GroupListViewController.swift
  ToDwoong/ToDwoong/Presentation/TabBar/TabBarController.swift
  ToDwoong/ToDwoong/Presentation/TodoList/View/GroupCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/TodoList/ViewController/TodoListViewController.swift
Labels: Feat

#106 [Chore]#105-투두, 캘린더 테이블뷰 UI 수정
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoViewController.swift
  ToDwoong/ToDwoong/Presentation/Calander/ViewController/CalanderViewController.swift
  ToDwoong/ToDwoong/Presentation/TodoList/ViewController/TodoListViewController.swift
Labels: Chore

#130 [Feat] #126 - 앱 배포 설정
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/AppIcon.appiconset/1024.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/AppIcon.appiconset/114.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/AppIcon.appiconset/120.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/AppIcon.appiconset/180.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/AppIcon.appiconset/29.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/AppIcon.appiconset/40.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/AppIcon.appiconset/57.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/AppIcon.appiconset/58.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/AppIcon.appiconset/60.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/AppIcon.appiconset/80.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/AppIcon.appiconset/87.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  ToDwoong/ToDwoong/Global/Support/Assets.xcassets/AppIcon.appiconset/Contents.json
  ToDwoong/ToDwoong/Info.plist
Labels: Feat

#128 [Chore] #117 투두리스트 세부사항 수정
  ToDwoong/ToDwoong/Presentation/Calander/ViewController/CalanderViewController.swift
  ToDwoong/ToDwoong/Presentation/TodoList/ViewController/TodoListViewController.swift
Labels: Chore

#131 [Feat]#109- 지도 페이지 UI작업
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ToDwoong/ToDwoong/Presentation/Map/View/CustomCategoryChip.swift
  ToDwoong/ToDwoong/Presentation/Map/View/MapView.swift
  ToDwoong/ToDwoong/Presentation/Map/View/TodoAnnotation.swift
  ToDwoong/ToDwoong/Presentation/Map/View/TodoDetailView.swift
  ToDwoong/ToDwoong/Presentation/Map/ViewController/MapViewController.swift
  ToDwoong/ToDwoong/Presentation/Map/ViewController/TodoDetailViewController.swift
  ToDwoong/ToDwoong/Presentation/ReusableView/GroupChipsView.swift
Labels: Feat

#132 [Feat]#108- 그룹 페이지 셀 색상 및 Edit연결
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong/Presentation/GroupList/View/AddGroupButton.swift
  ToDwoong/ToDwoong/Presentation/GroupList/View/ContentSizedViewCell.swift
  ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListTableViewCell.swift
  ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
  ToDwoong/ToDwoong/Presentation/GroupList/View/GroupTableView.swift
  ToDwoong/ToDwoong/Presentation/GroupList/ViewController/GroupListViewController.swift
  ToDwoong/ToDwoong/Presentation/Map/ViewController/MapViewController.swift
Labels: Feat, Fix

#134 [Refactor]#111-투두 추가 UI 변경 및 기능 추가
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ToDwoong/ToDwoong/Global/Protocols/AddTodoProtocols.swift
  ToDwoong/ToDwoong/Global/Protocols/ComponetsProtocols.swift
  ToDwoong/ToDwoong/Info.plist
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DatePickerCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DatePickerTableViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DateTimeOptionCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DateTimePickerContainerCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/GroupTableViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/InfoCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/LocationTableViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/PlaceAlarmTableViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/TimeAlarmTableViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/TitleCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/View/AddTodoView.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoDatePickerController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoPlaceAlarmViewController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoTimeAlarmViewController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoTimePickerController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoViewController.swift
  ToDwoong/ToDwoong/Presentation/Calender/ViewController/CalenderViewController.swift
  ToDwoong/ToDwoong/Presentation/ReusableView/InfoChipView.swift
Labels: Refator

#136 [Refactor]#133-강제 라이트모드 설정
  ToDwoong/ToDwoong.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Refator

#141 [Fix] #140 - 리젝 사유 수정
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong/Info.plist
Labels: Fix

#147 [Fix]#139 투두추가 UI 버그 및 개선점 수정
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ToDwoong/ToDwoong/Global/Protocols/AddTodoProtocols.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DatePickerTableViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/GroupTableViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/LocationTableViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/PlaceAlarmTableViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/TimeAlarmTableViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Modals/DatePickerModal.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Modals/GroupSelectModal.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Modals/PlaceAlarmModal.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Modals/TimeAlarmModal.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Modals/TimePickerModal.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoAlarmViewController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoDatePickerController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoLocationPickerViewController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoTimePickerController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoViewController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Views/AddTodoLocationPickerView.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Views/AddTodoView.swift
  ToDwoong/ToDwoong/Presentation/ReusableView/InfoChipView.swift
Labels: Fix

#143 [Feat] #138 - 그룹리스트, 맵 페이지 NotificationCenter 추가 완료
  ToDwoong/ToDwoong/Presentation/AddGroup/ViewController/AddGroupViewController.swift
  ToDwoong/ToDwoong/Presentation/GroupList/ViewController/GroupListViewController.swift
  ToDwoong/ToDwoong/Presentation/Map/ViewController/MapViewController.swift
  ToDwoong/ToDwoong/Presentation/Map/ViewController/TodoDetailViewController.swift
Labels: Feat

#159 [Setting] #121 - 디자인시스템 라이브러리 버전 업데이트
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Setting

#164 [Chore]#150-투두 추가 페이지 날짜 UI 및 기능 변경
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DatePickerTableViewCell.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Modals/DatePickerModal.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Modals/TimePickerModal.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoViewController.swift
  ToDwoong/ToDwoong/Presentation/ReusableView/InfoChipView.swift
Labels: Chore

#169 [Fix]#155 투두추가 위치 지도 UI 및 기능수정
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ToDwoong/ToDwoong/Global/CoreData/CoreDataModel.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoLocationPickerViewController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoViewController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/LocationSearchViewController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Views/AddTodoLocationPickerView.swift
Labels: Fix

#173 [Feat]#163-삭제 시 경고 alert 추가
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong/Presentation/AlertController.swift
  ToDwoong/ToDwoong/Presentation/Calender/ViewController/CalenderViewController.swift
  ToDwoong/ToDwoong/Presentation/GroupList/ViewController/GroupListViewController.swift
  ToDwoong/ToDwoong/Presentation/TodoList/ViewController/TodoListViewController.swift
Labels: Feat

#172 [Feat] #153 - 지도 페이지 구현
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ToDwoong/ToDwoong/Global/CoreData/CoreDataManager.swift
  ToDwoong/ToDwoong/Global/CoreData/CoreDataModel.swift
  ToDwoong/ToDwoong/Global/Extensions/Notification+Extension.swift
  ToDwoong/ToDwoong/Global/Extensions/UIImage+Extension.swift
  ToDwoong/ToDwoong/Presentation/AddGroup/ViewController/AddGroupViewController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Modals/GroupSelectModal.swift
  ToDwoong/ToDwoong/Presentation/GroupList/ViewController/GroupListViewController.swift
  ToDwoong/ToDwoong/Presentation/Map/Model/TodoAnnotation.swift
  ToDwoong/ToDwoong/Presentation/Map/View/MapView.swift
  ToDwoong/ToDwoong/Presentation/Map/View/TodoDetailView.swift
  ToDwoong/ToDwoong/Presentation/Map/ViewController/MapViewController.swift
  ToDwoong/ToDwoong/Presentation/Map/ViewController/MapViewController2.swift
  ToDwoong/ToDwoong/Presentation/Map/ViewController/TodoDetailViewController.swift
  ToDwoong/ToDwoong/Presentation/ReusableView/GroupChipsView.swift
  ToDwoong/ToDwoong/Presentation/TodoList/View/GroupCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/TodoList/ViewController/TodoListViewController.swift
Labels: Feat

#174 [Feat] #120 - 코어데이터 CRUD 수정
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong/Global/App/AppDelegate.swift
  ToDwoong/ToDwoong/Global/CoreData/CoreDataManager.swift
  ToDwoong/ToDwoong/Global/CoreData/CoreDataModel.swift
  ToDwoong/ToDwoong/Global/CoreData/CoreDataProtocol.swift
  ToDwoong/ToDwoong/Global/CoreData/Model.xcdatamodeld/Model.xcdatamodel/contents
  ToDwoong/ToDwoong/Global/CoreData/ToDwoongModel.xcdatamodeld/Model.xcdatamodel/contents
  ToDwoong/ToDwoong/Global/Extensions/Notification+Extension.swift
  ToDwoong/ToDwoong/Global/Extensions/TodoAndCategory+Extension.swift
  ToDwoong/ToDwoong/Global/Extensions/UIImage+Extension.swift
  ToDwoong/ToDwoong/Global/Protocols/AddTodoProtocols.swift
  ToDwoong/ToDwoong/Presentation/AddGroup/ViewController/AddGroupViewController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Modals/GroupSelectModal.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoLocationPickerViewController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoViewController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/LocationSearchViewController.swift
  ToDwoong/ToDwoong/Presentation/AddTodo/Views/AddTodoLocationPickerView.swift
  ToDwoong/ToDwoong/Presentation/Calender/ViewController/CalenderViewController.swift
  ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListTableViewCell.swift
  ToDwoong/ToDwoong/Presentation/GroupList/ViewController/GroupListViewController.swift
  ToDwoong/ToDwoong/Presentation/Map/Model/TodoAnnotation.swift
  ToDwoong/ToDwoong/Presentation/Map/View/MapView.swift
  ToDwoong/ToDwoong/Presentation/Map/View/TodoDetailView.swift
  ToDwoong/ToDwoong/Presentation/Map/ViewController/MapViewController.swift
  ToDwoong/ToDwoong/Presentation/Map/ViewController/MapViewController2.swift
  ToDwoong/ToDwoong/Presentation/Map/ViewController/TodoDetailViewController.swift
  ToDwoong/ToDwoong/Presentation/Reusable/AlertController.swift
  ToDwoong/ToDwoong/Presentation/Reusable/FloatingButton.swift
  ToDwoong/ToDwoong/Presentation/Reusable/GroupChipsView.swift
  ToDwoong/ToDwoong/Presentation/Reusable/InfoChipView.swift
  ToDwoong/ToDwoong/Presentation/TabBar/TabBarController.swift
  ToDwoong/ToDwoong/Presentation/TodoList/View/GroupCollectionViewCell.swift
  ToDwoong/ToDwoong/Presentation/TodoList/View/TodoListTableViewCell.swift
  ToDwoong/ToDwoong/Presentation/TodoList/View/TodoListView.swift
  ToDwoong/ToDwoong/Presentation/TodoList/ViewController/TodoListViewController.swift
Labels: Feat

#176 [Feat] #161 - 앱 첫 진입시 제스처 가이드 제공하기
  ToDwoong/ToDwoong/Global/App/SceneDelegate.swift
Labels: Feat

#177 [Feat] #162 - 더블탭 제스처 구현
  ToDwoong/ToDwoong/Presentation/Calender/ViewController/CalenderViewController.swift
  ToDwoong/ToDwoong/Presentation/TodoList/ViewController/TodoListViewController.swift
Labels: Feat

#181 [Fix]#178-투두 위치 저장값 위치 연동오류 수정
  ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoLocationPickerViewController.swift
Labels: Fix

#182 [Fix] #180 - 지도 페이지 수정
  ToDwoong/ToDwoong/Presentation/Map/ViewController/MapViewController.swift
  ToDwoong/ToDwoong/Presentation/Map/ViewController/TodoDetailViewController.swift
  ToDwoong/ToDwoong/Presentation/TodoList/View/TodoListTableViewCell.swift
Labels: Fix

#185 [Fix]#183-투두 수정 그룹삭제 문제 해결
  ToDwoong/ToDwoong/Global/CoreData/CoreDataManager.swift
Labels: Bug, Fix

#187 [Feat] #184 - 지도 페이지 로직 수정
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong/Global/Protocols/MapViewProtocols.swift
  ToDwoong/ToDwoong/Presentation/Calender/ViewController/CalenderViewController.swift
  ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
  ToDwoong/ToDwoong/Presentation/Map/View/TodoDetailView.swift
  ToDwoong/ToDwoong/Presentation/Map/ViewController/MapViewController.swift
  ToDwoong/ToDwoong/Presentation/Map/ViewController/TodoDetailViewController.swift
  ToDwoong/ToDwoong/Presentation/Reusable/FloatingButton.swift
  ToDwoong/ToDwoong/Presentation/TodoList/View/TodoListView.swift
Labels: Bug, Fix

#193 [Feat] #192 - 위치 저장된 투두 없을 시 자기 위치를 줌 하기
  ToDwoong/ToDwoong.xcodeproj/project.pbxproj
  ToDwoong/ToDwoong/Presentation/Map/ViewController/MapViewController.swift
Labels: Fix

#196 [Chore]#195-닫기버튼 간격조절. 주석 삭제.
  ToDwoong/ToDwoong/Presentation/AddTodo/Views/AddTodoLocationPickerView.swift
Labels: Chore
